"""empty message

Revision ID: 062630a3b71b
Revises: 
Create Date: 2019-04-23 09:56:56.807151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062630a3b71b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usergroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.UnicodeText(), nullable=False),
    sa.Column('usergroup_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.UnicodeText(), nullable=False),
    sa.Column('password', sa.UnicodeText(), nullable=False),
    sa.Column('role', sa.Enum('uploader', 'compiler', 'manager'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usergroup_id'], ['usergroups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('templatefiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('log_date_time', sa.DateTime(), nullable=False),
    sa.Column('action', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compilations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('draft_deadline', sa.DateTime(), nullable=False),
    sa.Column('final_deadline', sa.DateTime(), nullable=False),
    sa.Column('templatefile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['templatefile_id'], ['templatefiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templatefilesheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('templatefile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('sheet_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['templatefile_id'], ['templatefiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploadedfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('compilation_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('filename', sa.UnicodeText(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('type', sa.Enum('submission', 'supplementary'), nullable=False),
    sa.ForeignKeyConstraint(['compilation_id'], ['compilations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploadedfiles')
    op.drop_table('templatefilesheets')
    op.drop_table('compilations')
    op.drop_table('userlog')
    op.drop_table('templatefiles')
    op.drop_table('users')
    op.drop_table('usergroups')
    # ### end Alembic commands ###
